---
title: "Taller: Estad铆stica Descriptiva para la Evaluaci贸n de la Calidad UAM-X"
listing:
  contents: posts
  sort: "title"
  type: default
  categories: false
  sort-ui: false
  filter-ui: false
page-layout: full
title-block-banner: true
---

隆Hola! Te doy la bienvenida. El objetivo de este taller es ofrecer una visi贸n general del papel de la estad铆stica descriptiva en la evaluaci贸n y control de calidad. Tambi茅n se abordan algunas de las herramientas que se utilizan para este fin, tales como el diagrama de Pareto o los diagramas de control.

En este mini sitio puedes encontrar todos los materiales del taller organizados por tema. Al final se incluye una secci贸n con algunos ejercicios propuestos relacionados con la industria postcosecha. El contenido completo del taller junto a otros materiales de utilidad se pueden descargar directamente en el siguiente enlace: [Documentos Taller Calidad UAMX](https://1drv.ms/f/s!Aq-N_KPbPrx08wV2DCYYjxhmXC5g?e=wzaJz4).

Espero que lo visto en el taller te sea de utilidad. 隆Hasta pronto!

火
